spring.datasource.url=jdbc:postgresql://ep-purple-band-a1kp70rs-pooler.ap-southeast-1.aws.neon.tech/sqlfirstone?sslmode=require
#sqlfirstone is the db
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VyMNcQ6XFT3E
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
