package com.example.demo.service;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import java.util.Map;

@Service
public class CaptchaVerificationService {

    @Value("${RECAPTCHA_SECRET}")
    private String secret;

    public boolean verifyCaptcha(String captchaToken) {
        //I am the owner of this website (using secret key).Please verify whether this captcha token was actually generated by Google.
        String url = "https://www.google.com/recaptcha/api/siteverify" + "?secret=" + secret + "&response=" + captchaToken;
        RestTemplate restTemplate = new RestTemplate();
        Map response = restTemplate.postForObject(url, null, Map.class); // key values pairs could be of different types
        return response != null && Boolean.TRUE.equals(response.get("success"));
    }
}